### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by RnoHach**
Hi Patrick, this is my first ever pull request so it'll most likely not be all proper. That being said, I want this to be its very best, so if you notice any issues please let me know and I will try to correct them. 
My main concern is that I may have translated things that should not have been translated, such as commands or whatnot. If you notice anything like that, feel free to correct things or inform me on what line is the issue so I can fix it. 
I will continue translating today, hoping to finish the first pass and start on QC. 

Thanks, cheers, much love and Dogecoing to the Moon! :-

### CODE REVIEW

**Comment by patricklodder** [comment]
Hi! Awesome ❤️

Like we expected earlier when we were talking on Reddit, there are some conflicts because of the update I did to the new strings that came between you starting work on this and now. I propose we fix these and any command changes, and then you should be able to do a real pull request on `dogecoin/dogecoin` directly (so that others can help you too and you don't depend just on me).

Let me know when you're done for today, and I will have a look at what exactly changed (the conflicts are displayed to be greater than reality), and will get you a non-conflicted work branch and go over any possible command translations and highlight those for you.

**Comment by RnoHach** [comment]
Okay, that sounds good! I may need some guidance with the real pull request, as I don't fully understand this process, but everything else sounds good and reasonable, and wow!
I will comment here when done for today. Thanks again!!

**Comment by RnoHach** [comment]
First pass (rough draft) is now complete. 

Awaiting instructions... (most responsive on twitter)

Thanks! Much Wow!

**Comment by patricklodder** [comment]
I have resolved the conflicts and annotated your commits with my conflict resolutions. Because some source strings have changed, I have retained the `unfinished` tags on these whilst retaining your translations, so we can easily identify them in case you want to change something because the translation doesn't cover the new source string.

I have also added one more commit that removes all the sources marked as `vanished`, because those don't need to be translated - save work 😁

The following lines now have `unfinished` tags: 927, 1414, 1418, 1426, 1438, 1442, 1446, 1549, 1758, 1770, 2218, 2372, 3114, 3654, 3690, 3710, 3826

I will now look at the commands you mentioned.

Edit: line numbers changed after taking care of some additional technical issues - updated them

**Comment by patricklodder** [comment]
I have fixed 3 technical errors:
- Cyrillic char in a tag on line 380
- `=` in a tag on line 590
- "numerous form" wasn't needed because the translation already takes care of plurality intrinsically.

And have fixed 4 issues with command translations:
- `help` as a command doesn't get translated.
- `-proxy` was translated
- 2 times, `-discardthreshold` had C&P errors, fixed those too

One last thing: on line 3786 there is a translation from `MiB` into `??` - probably needs a look

**Comment by patricklodder** [comment]
Fixed the technical errors that were causing exceptions. Waiting for build to finish to provide binary.

**Comment by CHANDRAMA2** [comment]
Hello

Chandrama mahato

**Pull request closed without merging**
